### ISSUE TITLE
point_cloud.ply

### ISSUE THREAD

**Issue by goometasoft** [ingra14m/Specular-Gaussians#7]
point_cloud.ply

**Comment by ingra14m** [comment]
Hi, thanks for your interest.

The point cloud in our project is not the same as vanilla 3D-GS, since we have a 24-dimension feature vector in without anchor version. I recommend you to check the point cloud in our project through MeshLab. Another interesting insight is that the number of point trained after ASG is less than vanilla 3D-GS.
